#pragma config(Sensor, S1,     color,          sensorEV3_Color, modeEV3Color_Reflected_Raw)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		while(){
	 		int cor;
	 		cor = getColorHue(S1);
			displayVariableValues(line1,cor);
		}
}
